name: Send Robinhood Portfolio Email

on:
  push:
    branches:
      - main          # Run workflow on pushes to the main branch
  schedule:
    - cron: '0 13 * * 1-5'   # Market open (13:00 UTC = 9:00 AM ET)
    - cron: '0 20 * * 1-5'   # Market close (20:00 UTC = 4:00 PM ET)
  workflow_dispatch:         # Manual trigger from GitHub UI

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install matplotlib robin_stocks

      - name: Run script
        env:
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
          RH_USERNAME: ${{ secrets.RH_USERNAME }}
          RH_PASSWORD: ${{ secrets.RH_PASSWORD }}
        run: python send_email.py
